{% set name = "rxcpp" %}
{% set version = "4.1.1" %}
{% set sha256 = "054a9be63e66904ecaa552ce56d6458b4545d6da5ea32f5103c7fc379cebb374" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/Reactive-Extensions/RxCpp/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

# WARNING: this source doesn't include the Catch submodule, which is used for
#          the test commands. It's not used for the examples, and we can just
#          ignore it there.

build:
  number: 0
  script:
    - cd projects
    - mkdir build
    - cd build

    - cmake -G"Unix Makefiles"  -DCMAKE_INSTALL_PREFIX=$PREFIX          ../CMake  # [unix]
    - cmake -G"NMake Makefiles" -DCMAKE_INSTALL_PREFIX=%LIBRARY_PREFIX% ../CMake  # [win]
    - if errorlevel 1 exit 1  # [win]

    # Run a quick build test that things are sensible.
    - make  println && examples/println/println    # [unix]
    - nmake println && examples\\println\\println  # [win]
    - if errorlevel 1 exit 1  # [win]

    # Install header files (won't install tests/examples):
    - make install   # [unix]
    - nmake install  # [win]
    - if errorlevel 1 exit 1  # [win]
  skip: true  # [win and vc<14]

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  # NOTE: rxcpp is header-only, but we still need compilers, etc. to install

test:
  commands:
    - test -f $PREFIX/include/rxcpp/rx-util.hpp              # [unix]
    - if not exist %LIBRARY_INC%\\rxcpp\\rx-util.hpp exit 1  # [win]

about:
  home: https://github.com/Reactive-Extensions/RxCpp
  license: Apache-2.0
  license_family: Apache
  license_file: license.md
  summary: Reactive Extensions for C++
  description: |
    The Reactive Extensions for C++ (RxCpp) is a library of algorithms for
    values-distributed-in-time.
  doc_url: http://reactive-extensions.github.io/RxCpp/
  dev_url: https://github.com/Reactive-Extensions/RxCpp

extra:
  recipe-maintainers:
    - djsutherland
