appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: bklcBtS04rxegDJvukiEPH/7pOdBS7QhkMy2skhSdxqIO1bCjG69UrkuyXNX7hvaU6/ixbRLZ8Veztxk5J3xBPiy1K8l72IFNIrAJ7BuYE7my0lkgg9MQsuNXs0ETJkuZj/gZVfMUwxIaL5iYVceWjzGFzeQogw+JSZulAqYIIT5KljwjvOdNXOV2FzxnARHM+OLa9NJZQ7NK+1QgVyp2Oke9araBAkYt3HzPG4nnzMDKIQWPPEYaFqnpuCp+Egx6sEIXZMWpC/nN6D8/Eba4ZecMixN35Epn9bZCkmFUeDGuo9Z/ofREibLMEpl4bbs9EhUHxQHPR2UDBWbR0eHziZlSNczxEPXXiOX4KKQpPRC0iMKewql2T3XITB4XRSr4BDmbQ+AkB8URjgcFhyeVI2ZAmneuSMQMha424FgaT7tq64I/WVog2cgrSGz25Eub/83pZm/S+92p9sxONEeXdf5TuFNPX9O1rA15FwQMPvbAQIIBE10ypRvp2/ekUu7/oRweRiqFcl8QKT11kvtuVwFx2YhDU27nkc21EAZDs43eQNvO6P/Gp66xQet6Ml1Avaf3q6YE6TuzwZsjR1j2JULHy8Gy73P6gKZgRcykRpBvmniEzkajSWskabIEvi2iLPXfheLS66aY12exvSumtneZ6CX3yGDjtFr5JumzUc=}
conda_forge_output_validation: true
